[package]
authors = ["Andre Bogus <bogusandre@gmail.com>"]
categories = ["development-tools::testing"]
description = "Derives arbitrary traits"
edition = "2018"
keywords = ["arbitrary", "testing", "derive", "macro"]
license = "MIT/Apache-2.0"
name = "derive_arbitrary"
readme = "README.md"
repository = "https://github.com/nagisa/rust_arbitrary"
version = "0.1.0"

[dependencies]
arbitrary = "0.2.0"
proc-macro2 = "0.4"
syn = "0.14"
synstructure = "0.9"

[lib]
proc_macro = true
